version: '{build}'
clone_folder: c:\projects\fluid
pull_requests:
  do_not_increment_build_number: true
configuration: Release
branches:
  except:
    - /^(?i:continuous)$/
skip_tags: true
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QT_PROFILE: msvc2015
      QTDIR: C:\Qt\5.10.1\msvc2015
      CMAKE_GENERATOR: "Visual Studio 14 2015"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      QT_PROFILE: msvc2017_64
#      QTDIR: C:\Qt\5.10.1\msvc2017_64
#      CMAKE_GENERATOR: "Visual Studio 15 2017"
init:
  - set PATH=%QTDIR%\bin;%PATH%
build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DLIRI_BUILD_TESTING:BOOL=OFF -DFLUID_WITH_DOCUMENTATION:BOOL=OFF .. -G "%CMAKE_GENERATOR%"
  - cmake --build .
#test_script:
#  - ctest -V -C Debug
notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#events'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
