sudo: required

arch:
  packages:
    - qt5-declarative
    - qt5-quickcontrols2
    - qt5-graphicaleffects
    - qt5-svg
    - cmake
    - extra-cmake-modules
    - xorg-server-xvfb
    - git
  script:
    - scripts/fetch_icons.sh
    - cmake . -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make
    - sudo make install
    - xvfb-run -a -s "-screen 0 800x600x24" make check

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
  slack: qmlos:fdUqVmPzqPskEL1UBhqapZ0w
